version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    build: ./db
    ports:
      - "27017:27017"
    networks:
      - app-network

  ollama-service:
    build: ./ai-service
    ports:
      - "5001:5001"
    depends_on:
      - ai-service
    networks:
      - app-network

  pdf-convert-service:
    build: ./file-converter-service
    ports:
      - "5003:5003"
    networks:
      - app-network

  pdf-upload-service:
    build: ./pdf-service
    ports:
      - "5002:5002"
    networks:
      - app-network

  ai-service:
    build: ./ai  # AI-Service-Verzeichnis
    environment:
      - OLLAMA_HOST=http://ai-service:11434
    ports:
      - "11434:11434"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - ollama-service
      - pdf-convert-service
      - pdf-upload-service
      - ai-service
    networks:
      - app-network
